# Generated by Django 4.2.7 on 2023-11-27 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskID', models.CharField(max_length=200)),
                ('taskNum', models.IntegerField(default=1)),
                ('discription', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
