# Generated by Django 4.2.7 on 2023-11-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mytask',
            name='taskID',
        ),
        migrations.RemoveField(
            model_name='mytask',
            name='taskNum',
        ),
        migrations.AlterField(
            model_name='mytask',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
