# Generated by Django 4.2.7 on 2023-12-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
